import { createHmac, randomBytes } from "node:crypto";
import { isIP } from "node:net";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
const privateIp=(ip:string)=>/^127\.|^10\.|^192\.168\.|^169\.254\.|^0\.|^::1$|^fc|^fd|^fe80/i.test(ip)||(/^172\.(\d+)\./.test(ip)&&Number(ip.split(".")[1])>=16&&Number(ip.split(".")[1])<=31);
const enc=new TextEncoder(); const dec=new TextDecoder();
async function webhookKey(){const raw=process.env["STREAM_API_WEBHOOK_ENCRYPTION_KEY"];if(!raw)throw new Error("Webhook encryption unavailable");const digest=await crypto.subtle.digest("SHA-256",enc.encode(raw));return crypto.subtle.importKey("raw",digest,{name:"AES-GCM"},false,["encrypt","decrypt"]);}
const b64=(v:Uint8Array)=>Buffer.from(v).toString("base64url");
export async function encryptWebhookSecret(secret:string){const iv=crypto.getRandomValues(new Uint8Array(12));const value=await crypto.subtle.encrypt({name:"AES-GCM",iv},await webhookKey(),enc.encode(secret));return `wh:v1:${b64(iv)}.${b64(new Uint8Array(value))}`;}
export async function decryptWebhookSecret(value:string){const [iv,cipher]=value.replace("wh:v1:","").split(".");if(!iv||!cipher)throw new Error("Invalid webhook secret");const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:Buffer.from(iv,"base64url")},await webhookKey(),Buffer.from(cipher,"base64url"));return dec.decode(plain);}
export async function assertSafeWebhookUrl(raw:string){const url=new URL(raw);if(url.protocol!=="https:"||url.username||url.password||url.port)throw new Error("Webhook deve usar HTTPS padrão.");if(url.hostname==="localhost"||url.hostname.endsWith(".local")||(isIP(url.hostname)&&privateIp(url.hostname)))throw new Error("Destino privado não permitido.");const records=await Promise.all(["A","AAAA"].map(async type=>{try{const res=await fetch(`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(url.hostname)}&type=${type}`,{headers:{Accept:"application/dns-json"}});const j=await res.json() as any;return (j.Answer??[]).map((a:any)=>String(a.data));}catch{return[];}}));if(records.flat().some(privateIp))throw new Error("Destino privado não permitido.");return url;}
export function signWebhook(secret:string,timestamp:string,body:string){return `v1=${createHmac("sha256",secret).update(`${timestamp}.${body}`).digest("hex")}`;}
export async function deliverWebhook(deliveryId:string){const {data:d}=await supabaseAdmin.from("api_webhook_deliveries").select("id,attempt,api_webhooks(url,status,secret_ciphertext),api_webhook_events(event_id,event_type,payload,occurred_at)").eq("id",deliveryId).maybeSingle();if(!d)return;const hook=Array.isArray(d.api_webhooks)?d.api_webhooks[0]:d.api_webhooks;const event=Array.isArray(d.api_webhook_events)?d.api_webhook_events[0]:d.api_webhook_events;if(!hook||hook.status!=="active"||!event)return;await assertSafeWebhookUrl(hook.url);const secret=await decryptWebhookSecret(hook.secret_ciphertext);const body=JSON.stringify({id:event.event_id,type:event.event_type,occurred_at:event.occurred_at,data:event.payload});const timestamp=Math.floor(Date.now()/1000).toString();const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),8000);try{const res=await fetch(hook.url,{method:"POST",redirect:"manual",signal:ctrl.signal,headers:{"content-type":"application/json","user-agent":"StreamMonitor-Webhooks/1.0","x-stream-event":event.event_type,"x-stream-delivery":randomBytes(12).toString("hex"),"x-stream-timestamp":timestamp,"x-stream-signature":signWebhook(secret,timestamp,body)},body});if(res.status>=200&&res.status<300){await supabaseAdmin.from("api_webhook_deliveries").update({status:"delivered",response_status:res.status,delivered_at:new Date().toISOString()}).eq("id",d.id);return;}throw new Error(`HTTP ${res.status}`);}catch(e){const attempt=d.attempt+1;const delays=[60000,300000,900000,3600000];await supabaseAdmin.from("api_webhook_deliveries").update({attempt,status:attempt>=4?"failed":"retrying",error_code:e instanceof Error?e.message.slice(0,100):"delivery_error",next_attempt_at:attempt>=4?null:new Date(Date.now()+delays[Math.min(attempt-1,3)]).toISOString()}).eq("id",d.id);}finally{clearTimeout(timer);}}
