import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { clientIp, hashKey, sanitizeForLog } from "./api-security.server";

export const API_SCOPES = ["servers:read", "monitoring:read", "performance:read", "incidents:read", "analytics:read", "ai:read", "webhooks:manage"] as const;
export type ApiScope = typeof API_SCOPES[number];
export type ApiContext = { requestId:string; accountId:string; keyId:string; environment:"live"|"test"; scopes:Set<string>; monthlyLimit:number; minuteLimit:number; burstLimit:number; origin:string|null; ip:string };
export class CommercialApiError extends Error { constructor(public status:number, public code:string, message:string, public headers:Record<string,string>={}) { super(message); } }
const env = (name:string) => { const value=process.env[name]; if(!value) throw new CommercialApiError(503,"api_unavailable","API temporariamente indisponível."); return value; };
const hmac = (value:string) => createHmac("sha256",env("STREAM_API_KEY_PEPPER")).update(value).digest("hex");
const equal = (a:string,b:string) => { const aa=Buffer.from(a); const bb=Buffer.from(b); return aa.length===bb.length && timingSafeEqual(aa,bb); };
export const makeId = (prefix:string) => `${prefix}_${randomBytes(18).toString("base64url")}`;
export function generateApiKey(environment:"live"|"test") { const prefix=randomBytes(6).toString("base64url"); const secret=randomBytes(32).toString("base64url"); const raw=`sm_${environment}_${prefix}_${secret}`; return {raw,prefix:`sm_${environment}_${prefix}`,hash:hmac(raw),lastFour:raw.slice(-4)}; }
export function apiKeyPrefix(raw:string) { return raw.split("_").slice(0,3).join("_"); }
function rawKey(request:Request) { const bearer=request.headers.get("authorization")?.match(/^Bearer\s+(.+)$/i)?.[1]?.trim(); const header=request.headers.get("x-api-key")?.trim(); if(bearer&&header&&bearer!==header) throw new CommercialApiError(401,"invalid_api_key","Credenciais divergentes."); return bearer||header||null; }
function requestId() { return makeId("req"); }
export async function authenticateApiRequest(request:Request, requiredScope?:ApiScope):Promise<ApiContext> {
 const id=requestId(); if(process.env.STREAM_API_ENABLED==="false") throw new CommercialApiError(503,"api_disabled","API temporariamente desativada.");
 const raw=rawKey(request); if(!raw||!/^sm_(live|test)_[A-Za-z0-9_-]+_[A-Za-z0-9_-]+$/.test(raw)) throw new CommercialApiError(401,"invalid_api_key","Chave de API ausente ou inválida.");
 const prefix=apiKeyPrefix(raw); const {data:key}=await supabaseAdmin.from("api_keys").select("id,account_id,subscription_id,environment,key_hash,status,expires_at,per_minute_limit_override").eq("key_prefix",prefix).maybeSingle();
 if(!key||!equal(hmac(raw),key.key_hash)) throw new CommercialApiError(401,"invalid_api_key","Chave de API ausente ou inválida.");
 if(key.status!=="active"||(key.expires_at&&new Date(key.expires_at)<=new Date())) throw new CommercialApiError(401,"inactive_api_key","Chave revogada, inativa ou expirada.");
 const {data:sub}=await supabaseAdmin.from("api_subscriptions").select("status,starts_at,expires_at,monthly_limit_override,per_minute_limit_override,burst_limit_override,extra_requests,api_plans(monthly_request_limit,per_minute_limit,burst_limit)").eq("id",key.subscription_id).eq("account_id",key.account_id).maybeSingle();
 if(!sub||!["trial","active"].includes(sub.status)||(sub.starts_at&&new Date(sub.starts_at)>new Date())||(sub.expires_at&&new Date(sub.expires_at)<=new Date())) throw new CommercialApiError(403,"subscription_inactive","Assinatura da API inativa.");
 const plan=Array.isArray(sub.api_plans)?sub.api_plans[0]:sub.api_plans; if(!plan) throw new CommercialApiError(403,"plan_unavailable","Plano da API indisponível.");
 const {data:scopeRows}=await supabaseAdmin.from("api_key_scopes").select("scope").eq("key_id",key.id).eq("account_id",key.account_id); const scopes=new Set((scopeRows??[]).map(x=>x.scope));
 if(requiredScope&&!scopes.has(requiredScope)) throw new CommercialApiError(403,"insufficient_scope",`Escopo necessário: ${requiredScope}.`);
 const ip=clientIp(request.headers); const {data:ips}=await supabaseAdmin.from("api_allowed_ips").select("cidr").eq("key_id",key.id); if((ips?.length??0)>0&&!ips?.some(x=>String(x.cidr).split("/")[0]===ip)) throw new CommercialApiError(403,"ip_not_allowed","IP não autorizado.");
 const origin=request.headers.get("origin"); if(origin){const {data:origins}=await supabaseAdmin.from("api_allowed_origins").select("origin").eq("account_id",key.account_id).or(`key_id.is.null,key_id.eq.${key.id}`); if((origins?.length??0)>0&&!origins?.some(x=>x.origin===origin)) throw new CommercialApiError(403,"origin_not_allowed","Origem não autorizada.");}
 const monthlyLimit=Number(sub.monthly_limit_override??plan.monthly_request_limit)+Number(sub.extra_requests??0); const minuteLimit=Number(key.per_minute_limit_override??sub.per_minute_limit_override??plan.per_minute_limit); const burstLimit=Number(sub.burst_limit_override??plan.burst_limit);
 const now=Date.now();const minuteStart=new Date(Math.floor(now/60000)*60000).toISOString(); const {data:rate}=await supabaseAdmin.rpc("api_consume_rate_limit",{p_bucket:"commercial-minute",p_key_hash:hashKey(key.id),p_window_start:minuteStart,p_limit:minuteLimit}); const hit=rate?.[0]; if(hit&&!hit.allowed) throw new CommercialApiError(429,"rate_limit_exceeded","Limite por minuto excedido.",{"Retry-After":"60"});const burstStart=new Date(Math.floor(now/10000)*10000).toISOString();const {data:burst}=await supabaseAdmin.rpc("api_consume_rate_limit",{p_bucket:"commercial-burst",p_key_hash:hashKey(key.id),p_window_start:burstStart,p_limit:burstLimit});if(burst?.[0]&&!burst[0].allowed)throw new CommercialApiError(429,"burst_limit_exceeded","Muitas solicitações simultâneas.",{"Retry-After":"10"});
 const {data:monthly}=await supabaseAdmin.rpc("api_monthly_usage",{p_account_id:key.account_id,p_environment:key.environment}); if(Number(monthly??0)>=monthlyLimit) throw new CommercialApiError(429,"monthly_quota_exceeded","Quota mensal excedida.");
 await supabaseAdmin.from("api_keys").update({last_used_at:new Date().toISOString()}).eq("id",key.id);
 return {requestId:id,accountId:key.account_id,keyId:key.id,environment:key.environment as "live"|"test",scopes,monthlyLimit,minuteLimit,burstLimit,origin,ip};
}
export function apiCors(ctx:ApiContext): Record<string, string> { return ctx.origin?{"Access-Control-Allow-Origin":ctx.origin,"Vary":"Origin"}:{}; }
export function apiResponse(ctx:ApiContext,data:unknown,status=200,meta:Record<string,unknown>={}) { return Response.json({data,meta:{request_id:ctx.requestId,generated_at:new Date().toISOString(),...meta}},{status,headers:{"Cache-Control":"private, no-store","X-Request-ID":ctx.requestId,"X-RateLimit-Limit":String(ctx.minuteLimit),...apiCors(ctx)}}); }
export function apiFailure(error:unknown, requestId=makeId("req")) { const known=error instanceof CommercialApiError; const status=known?error.status:500; const code=known?error.code:"internal_error"; const message=known?error.message:"Não foi possível concluir a solicitação."; return Response.json({error:{code,message,request_id:requestId}},{status,headers:{"Cache-Control":"no-store","X-Request-ID":requestId,...(known?error.headers:{})}}); }
export async function logApiRequest(ctx:ApiContext,request:Request,status:number,started:number,errorCode?:string) { const path=new URL(request.url).pathname.replace(/\/(srv|inc)_[A-Za-z0-9_-]+/g,"/:id"); await supabaseAdmin.from("api_request_logs").insert({request_id:ctx.requestId,account_id:ctx.accountId,key_id:ctx.keyId,environment:ctx.environment,method:request.method,endpoint:path,status_code:status,duration_ms:Math.max(0,Date.now()-started),ip_hash:hashKey(ctx.ip),user_agent:String(sanitizeForLog(request.headers.get("user-agent")??"")).slice(0,200),error_code:errorCode??null}); const day=new Date().toISOString().slice(0,10); await supabaseAdmin.rpc("api_record_usage",{p_usage_date:day,p_account_id:ctx.accountId,p_key_id:ctx.keyId,p_environment:ctx.environment,p_endpoint:path,p_status_code:status,p_duration_ms:Math.max(0,Date.now()-started)}); }
export async function publicId(accountId:string,type:"server"|"incident",internalId:string) { const candidate=makeId(type==="server"?"srv":"inc"); const {data,error}=await supabaseAdmin.rpc("api_get_or_create_resource_id",{p_account_id:accountId,p_resource_type:type,p_internal_id:internalId,p_public_id:candidate}); if(error||!data) throw new Error("public id unavailable"); return data; }
export async function resolvePublicId(accountId:string,type:"server"|"incident",id:string) { const {data}=await supabaseAdmin.from("api_resource_ids").select("internal_id").eq("account_id",accountId).eq("resource_type",type).eq("public_id",id).maybeSingle(); return data?.internal_id??null; }
