import { createFileRoute } from "@tanstack/react-router";
import { z } from "zod";
import { authenticateApiRequest, apiFailure, apiResponse, CommercialApiError, logApiRequest, publicId, type ApiContext, type ApiScope } from "@/lib/commercial-api.server";

const limitSchema=z.coerce.number().int().min(1).max(100).default(25);
const scopeFor=(path:string):ApiScope|undefined=>path.includes("performance")?"performance:read":path.startsWith("servers")?"servers:read":path.startsWith("incidents")?"incidents:read":path.startsWith("analytics")?"analytics:read":path.startsWith("ai")?"ai:read":path.startsWith("monitoring")?"monitoring:read":undefined;
const numberOrNull=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:null;
async function serverRows(ctx:ApiContext){const {supabaseAdmin}=await import("@/integrations/supabase/client.server"); const {data,error}=await supabaseAdmin.from("servers").select("id,name,description,category,current_status,dns_status,health_score,dns_health_score,last_checked_at,last_latency_ms,last_http_status,ssl_days_remaining,monitoring_paused,created_at,updated_at").eq("owner_id",ctx.accountId); if(error) throw error; return data??[];}
async function idsFor(ctx:ApiContext,rows:Array<{id:string}>){return new Map(await Promise.all(rows.map(async r=>[r.id,await publicId(ctx.accountId,"server",r.id)] as const)));}
function serverDto(row:any,id:string){return {id,name:row.name,description:row.description,category:row.category,status:row.current_status,dns:{status:row.dns_status,health_score:numberOrNull(row.dns_health_score)},monitoring:{paused:row.monitoring_paused,last_checked_at:row.last_checked_at,latency_ms:numberOrNull(row.last_latency_ms),http_status:numberOrNull(row.last_http_status),ssl_days_remaining:numberOrNull(row.ssl_days_remaining)},health_score:numberOrNull(row.health_score),created_at:row.created_at,updated_at:row.updated_at};}
function cursor(index:number){return Buffer.from(String(index)).toString("base64url");}
function parseCursor(value:string|null){if(!value)return 0; const n=Number(Buffer.from(value,"base64url").toString()); return Number.isInteger(n)&&n>=0?n:0;}
async function handle(request:Request,path:string,ctx:ApiContext){const {supabaseAdmin}=await import("@/integrations/supabase/client.server"); const url=new URL(request.url); const parts=path.split("/").filter(Boolean); const limit=limitSchema.parse(url.searchParams.get("limit")??25); const offset=parseCursor(url.searchParams.get("cursor"));
 if(path==="health") return apiResponse(ctx,{service:"stream-monitor-api",status:"operational",version:"v1",mode:"read_only"});
 const rows=await serverRows(ctx); const idMap=await idsFor(ctx,rows); const byPublic=(pid:string)=>rows.find(r=>idMap.get(r.id)===pid);
 if(path==="servers"){const status=url.searchParams.get("status"); const sort=url.searchParams.get("sort")??"name"; let filtered=status?rows.filter(r=>r.current_status===status):rows; filtered=[...filtered].sort(sort==="latency"?(a,b)=>(a.last_latency_ms??Infinity)-(b.last_latency_ms??Infinity):sort==="health"?(a,b)=>(b.health_score??-1)-(a.health_score??-1):(a,b)=>a.name.localeCompare(b.name)); const page=filtered.slice(offset,offset+limit); return apiResponse(ctx,page.map(r=>serverDto(r,idMap.get(r.id)??"")),200,{pagination:{limit,next_cursor:offset+limit<filtered.length?cursor(offset+limit):null,total:filtered.length}});}
 if(parts[0]==="servers"&&parts[1]){const row=byPublic(parts[1]); if(!row) throw new CommercialApiError(404,"resource_not_found","Recurso não encontrado."); const dto=serverDto(row,idMap.get(row.id)??""); if(parts.length===2||parts[2]==="status") return apiResponse(ctx,dto);
  if(parts[2]==="performance"){const {data}=await supabaseAdmin.from("server_perf_runs").select("measured_at,api_ms,open_ms,open_min_ms,open_max_ms,total_ms,samples,ok,state,error").eq("server_id",row.id).order("measured_at",{ascending:false}).limit(limit); return apiResponse(ctx,{server:dto,measurements:data??[]});}
  if(parts[2]==="health") return apiResponse(ctx,{server_id:dto.id,health_score:dto.health_score,dns:dto.dns,status:dto.status,signals:{latency_ms:dto.monitoring.latency_ms,ssl_days_remaining:dto.monitoring.ssl_days_remaining,last_checked_at:dto.monitoring.last_checked_at}});
  if(parts[2]==="history"){const days=z.coerce.number().int().min(1).max(30).default(7).parse(url.searchParams.get("days")??7); const from=new Date(Date.now()-days*86400000).toISOString().slice(0,10); const {data}=await supabaseAdmin.from("checks_daily").select("day,total,ups,downs,degraded,uptime_pct,incidents,avg_latency_ms,max_latency_ms").eq("server_id",row.id).gte("day",from).order("day"); return apiResponse(ctx,{server_id:dto.id,period_days:days,points:data??[]});}
 }
 if(path.startsWith("monitoring/")){if(path==="monitoring/status")return apiResponse(ctx,rows.map(r=>({server_id:idMap.get(r.id),name:r.name,status:r.current_status,dns_status:r.dns_status,last_checked_at:r.last_checked_at}))); const totals={total:rows.length,online:rows.filter(r=>r.current_status==="up").length,degraded:rows.filter(r=>r.current_status==="degraded").length,offline:rows.filter(r=>r.current_status==="down").length,unknown:rows.filter(r=>r.current_status==="unknown").length,dns_offline:rows.filter(r=>r.dns_status==="down"||r.dns_status==="offline").length}; if(path==="monitoring/summary"||path==="monitoring/health")return apiResponse(ctx,{...totals,average_health_score:rows.length?Math.round(rows.reduce((s,r)=>s+(r.health_score??0),0)/rows.length):null}); if(path==="monitoring/performance"){const ids=rows.map(r=>r.id); const {data}=ids.length?await supabaseAdmin.from("server_perf_runs").select("server_id,measured_at,api_ms,open_ms,total_ms,ok,state").in("server_id",ids).order("measured_at",{ascending:false}).limit(500):{data:[]}; const seen=new Set<string>(); return apiResponse(ctx,(data??[]).filter(x=>!seen.has(x.server_id)&&seen.add(x.server_id)).map(x=>({...x,server_id:idMap.get(x.server_id)})));} if(path==="monitoring/regions"){const ids=rows.map(r=>r.id); const from=new Date(Date.now()-86400000).toISOString(); const {data}=ids.length?await supabaseAdmin.from("region_checks").select("server_id,region_code,status,latency_ms,http_status,checked_at").in("server_id",ids).gte("checked_at",from).order("checked_at",{ascending:false}).limit(1000):{data:[]}; return apiResponse(ctx,(data??[]).map(x=>({...x,server_id:idMap.get(x.server_id)})));}}
  if(parts[0]==="incidents"){const serverIds=rows.map(r=>r.id); const {data}=serverIds.length?await supabaseAdmin.from("incidents").select("id,server_id,incident_type,started_at,ended_at,failure_count,last_check_at,reason,regions").in("server_id",serverIds).order("started_at",{ascending:false}).limit(200):{data:[]}; const incidentRows=data??[]; const incidentMap=new Map(await Promise.all(incidentRows.map(async r=>[r.id,await publicId(ctx.accountId,"incident",r.id)] as const))); if(parts[1]){const found=incidentRows.find(r=>incidentMap.get(r.id)===parts[1]);if(!found)throw new CommercialApiError(404,"resource_not_found","Recurso não encontrado.");return apiResponse(ctx,{...found,id:incidentMap.get(found.id),server_id:idMap.get(found.server_id)});} const page=incidentRows.slice(offset,offset+limit); return apiResponse(ctx,page.map(r=>({...r,id:incidentMap.get(r.id),server_id:idMap.get(r.server_id)})),200,{pagination:{limit,next_cursor:offset+limit<incidentRows.length?cursor(offset+limit):null,total:incidentRows.length}});}
 if(path.startsWith("analytics/")){const ranked=[...rows].map(r=>({server_id:idMap.get(r.id),name:r.name,status:r.current_status,health_score:r.health_score,latency_ms:r.last_latency_ms,last_checked_at:r.last_checked_at})).sort((a,b)=>(b.health_score??-1)-(a.health_score??-1)); if(path==="analytics/best-server")return apiResponse(ctx,ranked[0]??null); if(path==="analytics/worst-server")return apiResponse(ctx,ranked.at(-1)??null); if(path==="analytics/degraded")return apiResponse(ctx,ranked.filter(r=>r.status==="degraded"||r.status==="down")); if(path.includes("latency"))ranked.sort((a,b)=>(a.latency_ms??Infinity)-(b.latency_ms??Infinity)); if(path.includes("health"))ranked.sort((a,b)=>(b.health_score??-1)-(a.health_score??-1)); if(path==="analytics/anomalies")return apiResponse(ctx,ranked.filter(r=>r.status!=="up"||(r.health_score??100)<70||(r.latency_ms??0)>1500).map(r=>({...r,reasons:[r.status!=="up"?"status_degraded":null,(r.health_score??100)<70?"low_health":null,(r.latency_ms??0)>1500?"high_latency":null].filter(Boolean)}))); return apiResponse(ctx,ranked);}
 if(path.startsWith("ai/")){const degraded=rows.filter(r=>r.current_status!=="up"||(r.health_score??100)<70); const context={generated_at:new Date().toISOString(),total_servers:rows.length,online:rows.filter(r=>r.current_status==="up").length,degraded:degraded.length,servers:rows.map(r=>({id:idMap.get(r.id),name:r.name,status:r.current_status,dns_status:r.dns_status,health_score:r.health_score,latency_ms:r.last_latency_ms,last_checked_at:r.last_checked_at}))}; if(parts[1]==="server"&&parts[2]){const row=byPublic(parts[2]); return row?apiResponse(ctx,{server:serverDto(row,idMap.get(row.id)??""),recommendations:recommend(row)}):apiResponse(ctx,null,404);} if(path==="ai/recommendations")return apiResponse(ctx,degraded.map(r=>({server_id:idMap.get(r.id),name:r.name,recommendations:recommend(r)}))); if(path==="ai/anomalies")return apiResponse(ctx,degraded.map(r=>({server_id:idMap.get(r.id),name:r.name,status:r.current_status,health_score:r.health_score}))); return apiResponse(ctx,context);}
 throw new CommercialApiError(404,"not_found","Endpoint não encontrado.");
}
function recommend(r:any){const out=[] as string[]; if(r.dns_status==="down"||r.dns_status==="offline")out.push("Verificar resolução DNS antes de classificar o servidor como offline."); if(r.current_status==="down")out.push("Validar conectividade HTTP nas regiões configuradas."); if((r.last_latency_ms??0)>1500)out.push("Investigar aumento de latência e tempo de resposta."); if((r.health_score??100)<70)out.push("Revisar os sinais que reduziram o Health Score."); return out.length?out:["Nenhuma ação prioritária identificada."];}
export const Route=createFileRoute("/api/v1/$")({
 server:{handlers:{
  GET:async({request,params})=>{const started=Date.now();let ctx:ApiContext|undefined;try{const path=params._splat??"";ctx=await authenticateApiRequest(request,scopeFor(path));const response=await handle(request,path,ctx);await logApiRequest(ctx,request,response.status,started,response.status>=400?"not_found":undefined);return response;}catch(error){const response=apiFailure(error,ctx?.requestId);if(ctx)await logApiRequest(ctx,request,response.status,started,error instanceof Error?error.message.slice(0,80):"error");return response;}},
  OPTIONS:async({request})=>{const origin=request.headers.get("origin");let allowed=false;if(origin){const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const {data}=await supabaseAdmin.from("api_allowed_origins").select("id").eq("origin",origin).limit(1);allowed=Boolean(data?.length);}return new Response(null,{status:allowed?204:403,headers:{...(allowed&&origin?{"Access-Control-Allow-Origin":origin,Vary:"Origin"}:{}),"Access-Control-Allow-Methods":"GET, OPTIONS","Access-Control-Allow-Headers":"Authorization, X-API-Key, Content-Type","Access-Control-Max-Age":"600"}});},
 }},
});
