import { createFileRoute,Link } from "@tanstack/react-router";
import { Activity,ArrowRight,BookOpen,Braces,KeyRound,ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
export const Route=createFileRoute("/developers")({component:Developers,head:()=>({meta:[{title:"STREAM MONITOR API | Documentação"},{name:"description",content:"Documentação oficial da API de monitoramento para sistemas, apps, bots, automações e IA."},{property:"og:title",content:"STREAM MONITOR API | Documentação"},{property:"og:description",content:"Integre status, performance, incidentes e analytics do Stream Monitor."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]})});
const code=`curl https://streammonitor.site/api/v1/monitoring/summary \\\n  -H "Authorization: Bearer sm_live_..."`;
function Developers(){return <div className="min-h-screen bg-background text-foreground"><header className="border-b"><div className="max-w-6xl mx-auto h-16 px-4 flex items-center justify-between"><Link to="/" className="font-semibold flex items-center gap-2"><Activity className="h-5 w-5 text-primary"/>streammonitor<span className="text-primary">API</span></Link><div className="flex gap-2"><Link to="/developers/changelog"><Button variant="ghost">Changelog</Button></Link><Link to="/auth"><Button>Entrar</Button></Link></div></div></header><main><section className="border-b grid-bg"><div className="max-w-6xl mx-auto px-4 py-20"><Badge variant="outline">v1 · Read-only</Badge><h1 className="text-4xl md:text-6xl font-semibold mt-5 max-w-3xl">STREAM MONITOR API</h1><p className="text-lg text-muted-foreground mt-4 max-w-2xl">Dados reais de status, performance, incidentes, regiões e Health Score para seus próprios sistemas.</p><div className="flex flex-wrap gap-3 mt-8"><a href="/api/openapi.json"><Button><BookOpen className="h-4 w-4 mr-2"/>OpenAPI JSON</Button></a><a href="#primeira-requisicao"><Button variant="outline">Primeira requisição<ArrowRight className="h-4 w-4 ml-2"/></Button></a></div></div></section><section className="max-w-6xl mx-auto px-4 py-14 grid md:grid-cols-[240px_1fr] gap-10"><aside className="space-y-2 text-sm"><a href="#autenticacao" className="block text-primary">Autenticação</a><a href="#primeira-requisicao" className="block text-muted-foreground">Primeira requisição</a><a href="#endpoints" className="block text-muted-foreground">Endpoints</a><a href="#limites" className="block text-muted-foreground">Limites e erros</a></aside><article className="space-y-12 max-w-3xl"><Doc id="autenticacao" icon={KeyRound} title="Autenticação"><p>Envie sua chave em <code>Authorization: Bearer</code> ou <code>X-API-Key</code>. Cada chave possui escopos, expiração e limites próprios.</p></Doc><Doc id="primeira-requisicao" icon={Braces} title="Primeira requisição"><pre className="overflow-x-auto rounded-md border bg-card p-4 text-sm"><code>{code}</code></pre><p>Respostas usam <code>data</code> e <code>meta</code>. Erros usam <code>error.code</code>, <code>error.message</code> e <code>error.request_id</code>.</p></Doc><Doc id="endpoints" icon={BookOpen} title="Endpoints"><Endpoint p="/api/v1/servers" s="servers:read"/><Endpoint p="/api/v1/monitoring/summary" s="monitoring:read"/><Endpoint p="/api/v1/incidents" s="incidents:read"/><Endpoint p="/api/v1/analytics/ranking" s="analytics:read"/><Endpoint p="/api/v1/ai/context" s="ai:read"/></Doc><Doc id="limites" icon={ShieldCheck} title="Limites e segurança"><p>Limites por minuto e mensais são aplicados por conta e chave. IDs públicos são opacos; credenciais IPTV, hosts privados e IDs internos nunca aparecem.</p></Doc></article></section></main></div>}
function Doc({id,icon:I,title,children}:{id:string;icon:any;title:string;children:any}){return <section id={id} className="space-y-4 scroll-mt-20"><h2 className="text-2xl font-semibold flex items-center gap-2"><I className="h-5 w-5 text-primary"/>{title}</h2><div className="text-muted-foreground space-y-4">{children}</div></section>}
function Endpoint({p,s}:{p:string;s:string}){return <div className="flex flex-col sm:flex-row gap-2 sm:items-center sm:justify-between border-b py-3"><code className="text-foreground">GET {p}</code><Badge variant="outline">{s}</Badge></div>}
