import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Activity,Braces,Clock,ShieldAlert } from "lucide-react";
import { getApiAdminOverview,updateApiPlan } from "@/lib/commercial-api.functions";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
export function ApiManagementPanel(){const qc=useQueryClient();const get=useServerFn(getApiAdminOverview);const update=useServerFn(updateApiPlan);const q=useQuery({queryKey:["api-admin-overview"],queryFn:()=>get()});const m=useMutation({mutationFn:(p:any)=>update({data:p}),onSuccess:()=>qc.invalidateQueries({queryKey:["api-admin-overview"]})});const d=q.data;return <div className="space-y-5"><div><h2 className="text-xl font-semibold flex items-center gap-2"><Braces className="h-5 w-5 text-primary"/>STREAM MONITOR API</h2><p className="text-sm text-muted-foreground">Planos, clientes e observabilidade. A ativação ocorre automaticamente após o PIX.</p></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><K icon={Activity} l="Requisições 24h" v={d?.metrics.requests24h??0}/><K icon={ShieldAlert} l="Erros 5xx" v={d?.metrics.errors24h??0}/><K icon={Clock} l="P95" v={`${d?.metrics.p95??0} ms`}/><K icon={Clock} l="P99" v={`${d?.metrics.p99??0} ms`}/></div><div className="grid md:grid-cols-2 gap-3">{d?.plans.map((p:any)=><Card key={p.id}><CardHeader><div className="flex items-center justify-between"><CardTitle className="text-base">{p.name}</CardTitle><Badge variant={p.is_active?"default":"secondary"}>{p.is_active?"Ativo":"Inativo"}</Badge></div></CardHeader><CardContent className="text-sm space-y-3"><div className="grid grid-cols-3 gap-2 text-muted-foreground"><span>{Number(p.monthly_request_limit).toLocaleString("pt-BR")}/mês</span><span>{p.per_minute_limit}/min</span><span>{p.max_keys} chaves</span></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>m.mutate({id:p.id,isActive:!p.is_active,isPublic:p.is_public})}>{p.is_active?"Desativar":"Ativar"}</Button><Button size="sm" variant="outline" onClick={()=>m.mutate({id:p.id,isActive:p.is_active,isPublic:!p.is_public})}>{p.is_public?"Ocultar":"Publicar"}</Button></div></CardContent></Card>)}</div><Card><CardHeader><CardTitle className="text-base">Assinaturas da API</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/50"><tr><th className="p-3 text-left">Cliente</th><th className="p-3 text-left">Plano</th><th className="p-3 text-left">Status</th><th className="p-3 text-left">Ambiente</th></tr></thead><tbody>{d?.subscriptions.map((s:any)=><tr key={s.id} className="border-t"><td className="p-3">{s.profiles?.full_name??s.profiles?.email??"Conta"}</td><td className="p-3">{s.api_plans?.name??"—"}</td><td className="p-3"><Badge variant="outline">{s.status}</Badge></td><td className="p-3">{s.environment}</td></tr>)}</tbody></table></div></CardContent></Card></div>}
function K({icon:I,l,v}:{icon:any;l:string;v:string|number}){return <Card><CardContent className="p-4"><I className="h-4 w-4 text-primary"/><div className="text-xl font-semibold mt-2">{v}</div><div className="text-xs text-muted-foreground">{l}</div></CardContent></Card>}
