/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as RevendedorStreamMonitorRouteImport } from './routes/revendedor-stream-monitor'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MonitoramentoIptvRouteImport } from './routes/monitoramento-iptv'
import { Route as MonitoramentoDnsRouteImport } from './routes/monitoramento-dns'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DnsRouteImport } from './routes/dns'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertasTelegramRouteImport } from './routes/alertas-telegram'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusSlugRouteImport } from './routes/status.$slug'
import { Route as BlogComoEvitarQuedaIptvRouteImport } from './routes/blog.como-evitar-queda-iptv'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicRadarRouteImport } from './routes/api/public/radar'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedAppSubscriptionRouteImport } from './routes/_authenticated/app.subscription'
import { Route as AuthenticatedAppStoreRouteImport } from './routes/_authenticated/app.store'
import { Route as AuthenticatedAppResellerRouteImport } from './routes/_authenticated/app.reseller'
import { Route as AuthenticatedAppRankingRouteImport } from './routes/_authenticated/app.ranking'
import { Route as AuthenticatedAppRadarRouteImport } from './routes/_authenticated/app.radar'
import { Route as AuthenticatedAppPaginaRouteImport } from './routes/_authenticated/app.pagina'
import { Route as AuthenticatedAppHubRouteImport } from './routes/_authenticated/app.hub'
import { Route as AuthenticatedAppDetectorRouteImport } from './routes/_authenticated/app.detector'
import { Route as AuthenticatedAppConteudosRouteImport } from './routes/_authenticated/app.conteudos'
import { Route as AuthenticatedAppAlertsRouteImport } from './routes/_authenticated/app.alerts'
import { Route as AuthenticatedAppAjudaRouteImport } from './routes/_authenticated/app.ajuda'
import { Route as AuthenticatedAppAiIntegrationRouteImport } from './routes/_authenticated/app.ai-integration'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppAchievementsRouteImport } from './routes/_authenticated/app.achievements'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAppServersIndexRouteImport } from './routes/_authenticated/app.servers.index'
import { Route as AuthenticatedAppInteligenciaIndexRouteImport } from './routes/_authenticated/app.inteligencia.index'
import { Route as AuthenticatedAppHubIndexRouteImport } from './routes/_authenticated/app.hub.index'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicSitemapXmlRouteImport } from './routes/api/public/sitemap/xml'
import { Route as ApiPublicRobotsTxtRouteImport } from './routes/api/public/robots/txt'
import { Route as ApiPublicRegionsTargetsRouteImport } from './routes/api/public/regions/targets'
import { Route as ApiPublicRegionsReportRouteImport } from './routes/api/public/regions/report'
import { Route as ApiPublicCronNotificationsRouteImport } from './routes/api/public/cron/notifications'
import { Route as ApiPublicCronIptvNotificationsRouteImport } from './routes/api/public/cron/iptv-notifications'
import { Route as ApiPublicCronDigestRouteImport } from './routes/api/public/cron/digest'
import { Route as ApiPublicCronCheckRouteImport } from './routes/api/public/cron/check'
import { Route as ApiPublicCoreTaskRouteImport } from './routes/api/public/core/task'
import { Route as AuthenticatedAppServersNewRouteImport } from './routes/_authenticated/app.servers.new'
import { Route as AuthenticatedAppServersIdRouteImport } from './routes/_authenticated/app.servers.$id'
import { Route as AuthenticatedAppHubVerificationRouteImport } from './routes/_authenticated/app.hub.verification'
import { Route as AuthenticatedAppHubServicesRouteImport } from './routes/_authenticated/app.hub.services'
import { Route as AuthenticatedAppHubRankingRouteImport } from './routes/_authenticated/app.hub.ranking'
import { Route as AuthenticatedAppHubNewRouteImport } from './routes/_authenticated/app.hub.new'
import { Route as AuthenticatedAppHubMessagesRouteImport } from './routes/_authenticated/app.hub.messages'
import { Route as AuthenticatedAppHubDemandRouteImport } from './routes/_authenticated/app.hub.demand'
import { Route as AuthenticatedAppInteligenciaMediaIdRouteImport } from './routes/_authenticated/app.inteligencia.$media.$id'
import { Route as AuthenticatedAppHubUHandleRouteImport } from './routes/_authenticated/app.hub.u.$handle'
import { Route as AuthenticatedAppHubLIdRouteImport } from './routes/_authenticated/app.hub.l.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RevendedorStreamMonitorRoute = RevendedorStreamMonitorRouteImport.update({
  id: '/revendedor-stream-monitor',
  path: '/revendedor-stream-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoIptvRoute = MonitoramentoIptvRouteImport.update({
  id: '/monitoramento-iptv',
  path: '/monitoramento-iptv',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoDnsRoute = MonitoramentoDnsRouteImport.update({
  id: '/monitoramento-dns',
  path: '/monitoramento-dns',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsRoute = DnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasTelegramRoute = AlertasTelegramRouteImport.update({
  id: '/alertas-telegram',
  path: '/alertas-telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSlugRoute = StatusSlugRouteImport.update({
  id: '/status/$slug',
  path: '/status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogComoEvitarQuedaIptvRoute = BlogComoEvitarQuedaIptvRouteImport.update({
  id: '/como-evitar-queda-iptv',
  path: '/como-evitar-queda-iptv',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicRadarRoute = ApiPublicRadarRouteImport.update({
  id: '/api/public/radar',
  path: '/api/public/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSubscriptionRoute =
  AuthenticatedAppSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppStoreRoute = AuthenticatedAppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppResellerRoute =
  AuthenticatedAppResellerRouteImport.update({
    id: '/reseller',
    path: '/reseller',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRankingRoute = AuthenticatedAppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRadarRoute = AuthenticatedAppRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPaginaRoute = AuthenticatedAppPaginaRouteImport.update({
  id: '/pagina',
  path: '/pagina',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHubRoute = AuthenticatedAppHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDetectorRoute =
  AuthenticatedAppDetectorRouteImport.update({
    id: '/detector',
    path: '/detector',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConteudosRoute =
  AuthenticatedAppConteudosRouteImport.update({
    id: '/conteudos',
    path: '/conteudos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAlertsRoute = AuthenticatedAppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAjudaRoute = AuthenticatedAppAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAiIntegrationRoute =
  AuthenticatedAppAiIntegrationRouteImport.update({
    id: '/ai-integration',
    path: '/ai-integration',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAchievementsRoute =
  AuthenticatedAppAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppServersIndexRoute =
  AuthenticatedAppServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInteligenciaIndexRoute =
  AuthenticatedAppInteligenciaIndexRouteImport.update({
    id: '/inteligencia/',
    path: '/inteligencia/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHubIndexRoute =
  AuthenticatedAppHubIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppHubRoute,
  } as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSitemapXmlRoute = ApiPublicSitemapXmlRouteImport.update({
  id: '/api/public/sitemap/xml',
  path: '/api/public/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobotsTxtRoute = ApiPublicRobotsTxtRouteImport.update({
  id: '/api/public/robots/txt',
  path: '/api/public/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegionsTargetsRoute = ApiPublicRegionsTargetsRouteImport.update({
  id: '/api/public/regions/targets',
  path: '/api/public/regions/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegionsReportRoute = ApiPublicRegionsReportRouteImport.update({
  id: '/api/public/regions/report',
  path: '/api/public/regions/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronNotificationsRoute =
  ApiPublicCronNotificationsRouteImport.update({
    id: '/api/public/cron/notifications',
    path: '/api/public/cron/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronIptvNotificationsRoute =
  ApiPublicCronIptvNotificationsRouteImport.update({
    id: '/api/public/cron/iptv-notifications',
    path: '/api/public/cron/iptv-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDigestRoute = ApiPublicCronDigestRouteImport.update({
  id: '/api/public/cron/digest',
  path: '/api/public/cron/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCheckRoute = ApiPublicCronCheckRouteImport.update({
  id: '/api/public/cron/check',
  path: '/api/public/cron/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCoreTaskRoute = ApiPublicCoreTaskRouteImport.update({
  id: '/api/public/core/task',
  path: '/api/public/core/task',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppServersNewRoute =
  AuthenticatedAppServersNewRouteImport.update({
    id: '/servers/new',
    path: '/servers/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppServersIdRoute =
  AuthenticatedAppServersIdRouteImport.update({
    id: '/servers/$id',
    path: '/servers/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHubVerificationRoute =
  AuthenticatedAppHubVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedAppHubRoute,
  } as any)
const AuthenticatedAppHubServicesRoute =
  AuthenticatedAppHubServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAppHubRoute,
  } as any)
const AuthenticatedAppHubRankingRoute =
  AuthenticatedAppHubRankingRouteImport.update({
    id: '/ranking',
    path: '/ranking',
    getParentRoute: () => AuthenticatedAppHubRoute,
  } as any)
const AuthenticatedAppHubNewRoute = AuthenticatedAppHubNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAppHubRoute,
} as any)
const AuthenticatedAppHubMessagesRoute =
  AuthenticatedAppHubMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAppHubRoute,
  } as any)
const AuthenticatedAppHubDemandRoute =
  AuthenticatedAppHubDemandRouteImport.update({
    id: '/demand',
    path: '/demand',
    getParentRoute: () => AuthenticatedAppHubRoute,
  } as any)
const AuthenticatedAppInteligenciaMediaIdRoute =
  AuthenticatedAppInteligenciaMediaIdRouteImport.update({
    id: '/inteligencia/$media/$id',
    path: '/inteligencia/$media/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHubUHandleRoute =
  AuthenticatedAppHubUHandleRouteImport.update({
    id: '/u/$handle',
    path: '/u/$handle',
    getParentRoute: () => AuthenticatedAppHubRoute,
  } as any)
const AuthenticatedAppHubLIdRoute = AuthenticatedAppHubLIdRouteImport.update({
  id: '/l/$id',
  path: '/l/$id',
  getParentRoute: () => AuthenticatedAppHubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/alertas-telegram': typeof AlertasTelegramRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/dns': typeof DnsRoute
  '/mcp': typeof McpRoute
  '/monitoramento-dns': typeof MonitoramentoDnsRoute
  '/monitoramento-iptv': typeof MonitoramentoIptvRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revendedor-stream-monitor': typeof RevendedorStreamMonitorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/blog/como-evitar-queda-iptv': typeof BlogComoEvitarQuedaIptvRoute
  '/status/$slug': typeof StatusSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/achievements': typeof AuthenticatedAppAchievementsRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/ai-integration': typeof AuthenticatedAppAiIntegrationRoute
  '/app/ajuda': typeof AuthenticatedAppAjudaRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/conteudos': typeof AuthenticatedAppConteudosRoute
  '/app/detector': typeof AuthenticatedAppDetectorRoute
  '/app/hub': typeof AuthenticatedAppHubRouteWithChildren
  '/app/pagina': typeof AuthenticatedAppPaginaRoute
  '/app/radar': typeof AuthenticatedAppRadarRoute
  '/app/ranking': typeof AuthenticatedAppRankingRoute
  '/app/reseller': typeof AuthenticatedAppResellerRoute
  '/app/store': typeof AuthenticatedAppStoreRoute
  '/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/radar': typeof ApiPublicRadarRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/hub/demand': typeof AuthenticatedAppHubDemandRoute
  '/app/hub/messages': typeof AuthenticatedAppHubMessagesRoute
  '/app/hub/new': typeof AuthenticatedAppHubNewRoute
  '/app/hub/ranking': typeof AuthenticatedAppHubRankingRoute
  '/app/hub/services': typeof AuthenticatedAppHubServicesRoute
  '/app/hub/verification': typeof AuthenticatedAppHubVerificationRoute
  '/app/servers/$id': typeof AuthenticatedAppServersIdRoute
  '/app/servers/new': typeof AuthenticatedAppServersNewRoute
  '/api/public/core/task': typeof ApiPublicCoreTaskRoute
  '/api/public/cron/check': typeof ApiPublicCronCheckRoute
  '/api/public/cron/digest': typeof ApiPublicCronDigestRoute
  '/api/public/cron/iptv-notifications': typeof ApiPublicCronIptvNotificationsRoute
  '/api/public/cron/notifications': typeof ApiPublicCronNotificationsRoute
  '/api/public/regions/report': typeof ApiPublicRegionsReportRoute
  '/api/public/regions/targets': typeof ApiPublicRegionsTargetsRoute
  '/api/public/robots/txt': typeof ApiPublicRobotsTxtRoute
  '/api/public/sitemap/xml': typeof ApiPublicSitemapXmlRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/app/hub/': typeof AuthenticatedAppHubIndexRoute
  '/app/inteligencia/': typeof AuthenticatedAppInteligenciaIndexRoute
  '/app/servers/': typeof AuthenticatedAppServersIndexRoute
  '/app/hub/l/$id': typeof AuthenticatedAppHubLIdRoute
  '/app/hub/u/$handle': typeof AuthenticatedAppHubUHandleRoute
  '/app/inteligencia/$media/$id': typeof AuthenticatedAppInteligenciaMediaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/alertas-telegram': typeof AlertasTelegramRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/dns': typeof DnsRoute
  '/mcp': typeof McpRoute
  '/monitoramento-dns': typeof MonitoramentoDnsRoute
  '/monitoramento-iptv': typeof MonitoramentoIptvRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revendedor-stream-monitor': typeof RevendedorStreamMonitorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/como-evitar-queda-iptv': typeof BlogComoEvitarQuedaIptvRoute
  '/status/$slug': typeof StatusSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/achievements': typeof AuthenticatedAppAchievementsRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/ai-integration': typeof AuthenticatedAppAiIntegrationRoute
  '/app/ajuda': typeof AuthenticatedAppAjudaRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/conteudos': typeof AuthenticatedAppConteudosRoute
  '/app/detector': typeof AuthenticatedAppDetectorRoute
  '/app/pagina': typeof AuthenticatedAppPaginaRoute
  '/app/radar': typeof AuthenticatedAppRadarRoute
  '/app/ranking': typeof AuthenticatedAppRankingRoute
  '/app/reseller': typeof AuthenticatedAppResellerRoute
  '/app/store': typeof AuthenticatedAppStoreRoute
  '/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/radar': typeof ApiPublicRadarRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/hub/demand': typeof AuthenticatedAppHubDemandRoute
  '/app/hub/messages': typeof AuthenticatedAppHubMessagesRoute
  '/app/hub/new': typeof AuthenticatedAppHubNewRoute
  '/app/hub/ranking': typeof AuthenticatedAppHubRankingRoute
  '/app/hub/services': typeof AuthenticatedAppHubServicesRoute
  '/app/hub/verification': typeof AuthenticatedAppHubVerificationRoute
  '/app/servers/$id': typeof AuthenticatedAppServersIdRoute
  '/app/servers/new': typeof AuthenticatedAppServersNewRoute
  '/api/public/core/task': typeof ApiPublicCoreTaskRoute
  '/api/public/cron/check': typeof ApiPublicCronCheckRoute
  '/api/public/cron/digest': typeof ApiPublicCronDigestRoute
  '/api/public/cron/iptv-notifications': typeof ApiPublicCronIptvNotificationsRoute
  '/api/public/cron/notifications': typeof ApiPublicCronNotificationsRoute
  '/api/public/regions/report': typeof ApiPublicRegionsReportRoute
  '/api/public/regions/targets': typeof ApiPublicRegionsTargetsRoute
  '/api/public/robots/txt': typeof ApiPublicRobotsTxtRoute
  '/api/public/sitemap/xml': typeof ApiPublicSitemapXmlRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/app/hub': typeof AuthenticatedAppHubIndexRoute
  '/app/inteligencia': typeof AuthenticatedAppInteligenciaIndexRoute
  '/app/servers': typeof AuthenticatedAppServersIndexRoute
  '/app/hub/l/$id': typeof AuthenticatedAppHubLIdRoute
  '/app/hub/u/$handle': typeof AuthenticatedAppHubUHandleRoute
  '/app/inteligencia/$media/$id': typeof AuthenticatedAppInteligenciaMediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/alertas-telegram': typeof AlertasTelegramRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/dns': typeof DnsRoute
  '/mcp': typeof McpRoute
  '/monitoramento-dns': typeof MonitoramentoDnsRoute
  '/monitoramento-iptv': typeof MonitoramentoIptvRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revendedor-stream-monitor': typeof RevendedorStreamMonitorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/blog/como-evitar-queda-iptv': typeof BlogComoEvitarQuedaIptvRoute
  '/status/$slug': typeof StatusSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/app/achievements': typeof AuthenticatedAppAchievementsRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/ai-integration': typeof AuthenticatedAppAiIntegrationRoute
  '/_authenticated/app/ajuda': typeof AuthenticatedAppAjudaRoute
  '/_authenticated/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/_authenticated/app/conteudos': typeof AuthenticatedAppConteudosRoute
  '/_authenticated/app/detector': typeof AuthenticatedAppDetectorRoute
  '/_authenticated/app/hub': typeof AuthenticatedAppHubRouteWithChildren
  '/_authenticated/app/pagina': typeof AuthenticatedAppPaginaRoute
  '/_authenticated/app/radar': typeof AuthenticatedAppRadarRoute
  '/_authenticated/app/ranking': typeof AuthenticatedAppRankingRoute
  '/_authenticated/app/reseller': typeof AuthenticatedAppResellerRoute
  '/_authenticated/app/store': typeof AuthenticatedAppStoreRoute
  '/_authenticated/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/radar': typeof ApiPublicRadarRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/hub/demand': typeof AuthenticatedAppHubDemandRoute
  '/_authenticated/app/hub/messages': typeof AuthenticatedAppHubMessagesRoute
  '/_authenticated/app/hub/new': typeof AuthenticatedAppHubNewRoute
  '/_authenticated/app/hub/ranking': typeof AuthenticatedAppHubRankingRoute
  '/_authenticated/app/hub/services': typeof AuthenticatedAppHubServicesRoute
  '/_authenticated/app/hub/verification': typeof AuthenticatedAppHubVerificationRoute
  '/_authenticated/app/servers/$id': typeof AuthenticatedAppServersIdRoute
  '/_authenticated/app/servers/new': typeof AuthenticatedAppServersNewRoute
  '/api/public/core/task': typeof ApiPublicCoreTaskRoute
  '/api/public/cron/check': typeof ApiPublicCronCheckRoute
  '/api/public/cron/digest': typeof ApiPublicCronDigestRoute
  '/api/public/cron/iptv-notifications': typeof ApiPublicCronIptvNotificationsRoute
  '/api/public/cron/notifications': typeof ApiPublicCronNotificationsRoute
  '/api/public/regions/report': typeof ApiPublicRegionsReportRoute
  '/api/public/regions/targets': typeof ApiPublicRegionsTargetsRoute
  '/api/public/robots/txt': typeof ApiPublicRobotsTxtRoute
  '/api/public/sitemap/xml': typeof ApiPublicSitemapXmlRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/_authenticated/app/hub/': typeof AuthenticatedAppHubIndexRoute
  '/_authenticated/app/inteligencia/': typeof AuthenticatedAppInteligenciaIndexRoute
  '/_authenticated/app/servers/': typeof AuthenticatedAppServersIndexRoute
  '/_authenticated/app/hub/l/$id': typeof AuthenticatedAppHubLIdRoute
  '/_authenticated/app/hub/u/$handle': typeof AuthenticatedAppHubUHandleRoute
  '/_authenticated/app/inteligencia/$media/$id': typeof AuthenticatedAppInteligenciaMediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/alertas-telegram'
    | '/auth'
    | '/blog'
    | '/dns'
    | '/mcp'
    | '/monitoramento-dns'
    | '/monitoramento-iptv'
    | '/reset-password'
    | '/revendedor-stream-monitor'
    | '/verify-email'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/blog/como-evitar-queda-iptv'
    | '/status/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/achievements'
    | '/app/admin'
    | '/app/ai-integration'
    | '/app/ajuda'
    | '/app/alerts'
    | '/app/conteudos'
    | '/app/detector'
    | '/app/hub'
    | '/app/pagina'
    | '/app/radar'
    | '/app/ranking'
    | '/app/reseller'
    | '/app/store'
    | '/app/subscription'
    | '/api/public/health'
    | '/api/public/radar'
    | '/app/'
    | '/app/hub/demand'
    | '/app/hub/messages'
    | '/app/hub/new'
    | '/app/hub/ranking'
    | '/app/hub/services'
    | '/app/hub/verification'
    | '/app/servers/$id'
    | '/app/servers/new'
    | '/api/public/core/task'
    | '/api/public/cron/check'
    | '/api/public/cron/digest'
    | '/api/public/cron/iptv-notifications'
    | '/api/public/cron/notifications'
    | '/api/public/regions/report'
    | '/api/public/regions/targets'
    | '/api/public/robots/txt'
    | '/api/public/sitemap/xml'
    | '/api/public/telegram/webhook'
    | '/api/public/webhooks/mercadopago'
    | '/app/hub/'
    | '/app/inteligencia/'
    | '/app/servers/'
    | '/app/hub/l/$id'
    | '/app/hub/u/$handle'
    | '/app/inteligencia/$media/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/alertas-telegram'
    | '/auth'
    | '/blog'
    | '/dns'
    | '/mcp'
    | '/monitoramento-dns'
    | '/monitoramento-iptv'
    | '/reset-password'
    | '/revendedor-stream-monitor'
    | '/verify-email'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/como-evitar-queda-iptv'
    | '/status/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/achievements'
    | '/app/admin'
    | '/app/ai-integration'
    | '/app/ajuda'
    | '/app/alerts'
    | '/app/conteudos'
    | '/app/detector'
    | '/app/pagina'
    | '/app/radar'
    | '/app/ranking'
    | '/app/reseller'
    | '/app/store'
    | '/app/subscription'
    | '/api/public/health'
    | '/api/public/radar'
    | '/app'
    | '/app/hub/demand'
    | '/app/hub/messages'
    | '/app/hub/new'
    | '/app/hub/ranking'
    | '/app/hub/services'
    | '/app/hub/verification'
    | '/app/servers/$id'
    | '/app/servers/new'
    | '/api/public/core/task'
    | '/api/public/cron/check'
    | '/api/public/cron/digest'
    | '/api/public/cron/iptv-notifications'
    | '/api/public/cron/notifications'
    | '/api/public/regions/report'
    | '/api/public/regions/targets'
    | '/api/public/robots/txt'
    | '/api/public/sitemap/xml'
    | '/api/public/telegram/webhook'
    | '/api/public/webhooks/mercadopago'
    | '/app/hub'
    | '/app/inteligencia'
    | '/app/servers'
    | '/app/hub/l/$id'
    | '/app/hub/u/$handle'
    | '/app/inteligencia/$media/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/alertas-telegram'
    | '/auth'
    | '/blog'
    | '/dns'
    | '/mcp'
    | '/monitoramento-dns'
    | '/monitoramento-iptv'
    | '/reset-password'
    | '/revendedor-stream-monitor'
    | '/verify-email'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/app'
    | '/blog/como-evitar-queda-iptv'
    | '/status/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/app/achievements'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/ai-integration'
    | '/_authenticated/app/ajuda'
    | '/_authenticated/app/alerts'
    | '/_authenticated/app/conteudos'
    | '/_authenticated/app/detector'
    | '/_authenticated/app/hub'
    | '/_authenticated/app/pagina'
    | '/_authenticated/app/radar'
    | '/_authenticated/app/ranking'
    | '/_authenticated/app/reseller'
    | '/_authenticated/app/store'
    | '/_authenticated/app/subscription'
    | '/api/public/health'
    | '/api/public/radar'
    | '/_authenticated/app/'
    | '/_authenticated/app/hub/demand'
    | '/_authenticated/app/hub/messages'
    | '/_authenticated/app/hub/new'
    | '/_authenticated/app/hub/ranking'
    | '/_authenticated/app/hub/services'
    | '/_authenticated/app/hub/verification'
    | '/_authenticated/app/servers/$id'
    | '/_authenticated/app/servers/new'
    | '/api/public/core/task'
    | '/api/public/cron/check'
    | '/api/public/cron/digest'
    | '/api/public/cron/iptv-notifications'
    | '/api/public/cron/notifications'
    | '/api/public/regions/report'
    | '/api/public/regions/targets'
    | '/api/public/robots/txt'
    | '/api/public/sitemap/xml'
    | '/api/public/telegram/webhook'
    | '/api/public/webhooks/mercadopago'
    | '/_authenticated/app/hub/'
    | '/_authenticated/app/inteligencia/'
    | '/_authenticated/app/servers/'
    | '/_authenticated/app/hub/l/$id'
    | '/_authenticated/app/hub/u/$handle'
    | '/_authenticated/app/inteligencia/$media/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AlertasTelegramRoute: typeof AlertasTelegramRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  DnsRoute: typeof DnsRoute
  McpRoute: typeof McpRoute
  MonitoramentoDnsRoute: typeof MonitoramentoDnsRoute
  MonitoramentoIptvRoute: typeof MonitoramentoIptvRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RevendedorStreamMonitorRoute: typeof RevendedorStreamMonitorRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  StatusSlugRoute: typeof StatusSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicRadarRoute: typeof ApiPublicRadarRoute
  ApiPublicCoreTaskRoute: typeof ApiPublicCoreTaskRoute
  ApiPublicCronCheckRoute: typeof ApiPublicCronCheckRoute
  ApiPublicCronDigestRoute: typeof ApiPublicCronDigestRoute
  ApiPublicCronIptvNotificationsRoute: typeof ApiPublicCronIptvNotificationsRoute
  ApiPublicCronNotificationsRoute: typeof ApiPublicCronNotificationsRoute
  ApiPublicRegionsReportRoute: typeof ApiPublicRegionsReportRoute
  ApiPublicRegionsTargetsRoute: typeof ApiPublicRegionsTargetsRoute
  ApiPublicRobotsTxtRoute: typeof ApiPublicRobotsTxtRoute
  ApiPublicSitemapXmlRoute: typeof ApiPublicSitemapXmlRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revendedor-stream-monitor': {
      id: '/revendedor-stream-monitor'
      path: '/revendedor-stream-monitor'
      fullPath: '/revendedor-stream-monitor'
      preLoaderRoute: typeof RevendedorStreamMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento-iptv': {
      id: '/monitoramento-iptv'
      path: '/monitoramento-iptv'
      fullPath: '/monitoramento-iptv'
      preLoaderRoute: typeof MonitoramentoIptvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento-dns': {
      id: '/monitoramento-dns'
      path: '/monitoramento-dns'
      fullPath: '/monitoramento-dns'
      preLoaderRoute: typeof MonitoramentoDnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns': {
      id: '/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof DnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas-telegram': {
      id: '/alertas-telegram'
      path: '/alertas-telegram'
      fullPath: '/alertas-telegram'
      preLoaderRoute: typeof AlertasTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$slug': {
      id: '/status/$slug'
      path: '/status/$slug'
      fullPath: '/status/$slug'
      preLoaderRoute: typeof StatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/como-evitar-queda-iptv': {
      id: '/blog/como-evitar-queda-iptv'
      path: '/como-evitar-queda-iptv'
      fullPath: '/blog/como-evitar-queda-iptv'
      preLoaderRoute: typeof BlogComoEvitarQuedaIptvRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/radar': {
      id: '/api/public/radar'
      path: '/api/public/radar'
      fullPath: '/api/public/radar'
      preLoaderRoute: typeof ApiPublicRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/subscription': {
      id: '/_authenticated/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/store': {
      id: '/_authenticated/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AuthenticatedAppStoreRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reseller': {
      id: '/_authenticated/app/reseller'
      path: '/reseller'
      fullPath: '/app/reseller'
      preLoaderRoute: typeof AuthenticatedAppResellerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ranking': {
      id: '/_authenticated/app/ranking'
      path: '/ranking'
      fullPath: '/app/ranking'
      preLoaderRoute: typeof AuthenticatedAppRankingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/radar': {
      id: '/_authenticated/app/radar'
      path: '/radar'
      fullPath: '/app/radar'
      preLoaderRoute: typeof AuthenticatedAppRadarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pagina': {
      id: '/_authenticated/app/pagina'
      path: '/pagina'
      fullPath: '/app/pagina'
      preLoaderRoute: typeof AuthenticatedAppPaginaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hub': {
      id: '/_authenticated/app/hub'
      path: '/hub'
      fullPath: '/app/hub'
      preLoaderRoute: typeof AuthenticatedAppHubRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/detector': {
      id: '/_authenticated/app/detector'
      path: '/detector'
      fullPath: '/app/detector'
      preLoaderRoute: typeof AuthenticatedAppDetectorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/conteudos': {
      id: '/_authenticated/app/conteudos'
      path: '/conteudos'
      fullPath: '/app/conteudos'
      preLoaderRoute: typeof AuthenticatedAppConteudosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alerts': {
      id: '/_authenticated/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AuthenticatedAppAlertsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ajuda': {
      id: '/_authenticated/app/ajuda'
      path: '/ajuda'
      fullPath: '/app/ajuda'
      preLoaderRoute: typeof AuthenticatedAppAjudaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai-integration': {
      id: '/_authenticated/app/ai-integration'
      path: '/ai-integration'
      fullPath: '/app/ai-integration'
      preLoaderRoute: typeof AuthenticatedAppAiIntegrationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/achievements': {
      id: '/_authenticated/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AuthenticatedAppAchievementsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/servers/': {
      id: '/_authenticated/app/servers/'
      path: '/servers'
      fullPath: '/app/servers/'
      preLoaderRoute: typeof AuthenticatedAppServersIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inteligencia/': {
      id: '/_authenticated/app/inteligencia/'
      path: '/inteligencia'
      fullPath: '/app/inteligencia/'
      preLoaderRoute: typeof AuthenticatedAppInteligenciaIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hub/': {
      id: '/_authenticated/app/hub/'
      path: '/'
      fullPath: '/app/hub/'
      preLoaderRoute: typeof AuthenticatedAppHubIndexRouteImport
      parentRoute: typeof AuthenticatedAppHubRoute
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap/xml': {
      id: '/api/public/sitemap/xml'
      path: '/api/public/sitemap/xml'
      fullPath: '/api/public/sitemap/xml'
      preLoaderRoute: typeof ApiPublicSitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robots/txt': {
      id: '/api/public/robots/txt'
      path: '/api/public/robots/txt'
      fullPath: '/api/public/robots/txt'
      preLoaderRoute: typeof ApiPublicRobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/regions/targets': {
      id: '/api/public/regions/targets'
      path: '/api/public/regions/targets'
      fullPath: '/api/public/regions/targets'
      preLoaderRoute: typeof ApiPublicRegionsTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/regions/report': {
      id: '/api/public/regions/report'
      path: '/api/public/regions/report'
      fullPath: '/api/public/regions/report'
      preLoaderRoute: typeof ApiPublicRegionsReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/notifications': {
      id: '/api/public/cron/notifications'
      path: '/api/public/cron/notifications'
      fullPath: '/api/public/cron/notifications'
      preLoaderRoute: typeof ApiPublicCronNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/iptv-notifications': {
      id: '/api/public/cron/iptv-notifications'
      path: '/api/public/cron/iptv-notifications'
      fullPath: '/api/public/cron/iptv-notifications'
      preLoaderRoute: typeof ApiPublicCronIptvNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/digest': {
      id: '/api/public/cron/digest'
      path: '/api/public/cron/digest'
      fullPath: '/api/public/cron/digest'
      preLoaderRoute: typeof ApiPublicCronDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/check': {
      id: '/api/public/cron/check'
      path: '/api/public/cron/check'
      fullPath: '/api/public/cron/check'
      preLoaderRoute: typeof ApiPublicCronCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/core/task': {
      id: '/api/public/core/task'
      path: '/api/public/core/task'
      fullPath: '/api/public/core/task'
      preLoaderRoute: typeof ApiPublicCoreTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/servers/new': {
      id: '/_authenticated/app/servers/new'
      path: '/servers/new'
      fullPath: '/app/servers/new'
      preLoaderRoute: typeof AuthenticatedAppServersNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/servers/$id': {
      id: '/_authenticated/app/servers/$id'
      path: '/servers/$id'
      fullPath: '/app/servers/$id'
      preLoaderRoute: typeof AuthenticatedAppServersIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hub/verification': {
      id: '/_authenticated/app/hub/verification'
      path: '/verification'
      fullPath: '/app/hub/verification'
      preLoaderRoute: typeof AuthenticatedAppHubVerificationRouteImport
      parentRoute: typeof AuthenticatedAppHubRoute
    }
    '/_authenticated/app/hub/services': {
      id: '/_authenticated/app/hub/services'
      path: '/services'
      fullPath: '/app/hub/services'
      preLoaderRoute: typeof AuthenticatedAppHubServicesRouteImport
      parentRoute: typeof AuthenticatedAppHubRoute
    }
    '/_authenticated/app/hub/ranking': {
      id: '/_authenticated/app/hub/ranking'
      path: '/ranking'
      fullPath: '/app/hub/ranking'
      preLoaderRoute: typeof AuthenticatedAppHubRankingRouteImport
      parentRoute: typeof AuthenticatedAppHubRoute
    }
    '/_authenticated/app/hub/new': {
      id: '/_authenticated/app/hub/new'
      path: '/new'
      fullPath: '/app/hub/new'
      preLoaderRoute: typeof AuthenticatedAppHubNewRouteImport
      parentRoute: typeof AuthenticatedAppHubRoute
    }
    '/_authenticated/app/hub/messages': {
      id: '/_authenticated/app/hub/messages'
      path: '/messages'
      fullPath: '/app/hub/messages'
      preLoaderRoute: typeof AuthenticatedAppHubMessagesRouteImport
      parentRoute: typeof AuthenticatedAppHubRoute
    }
    '/_authenticated/app/hub/demand': {
      id: '/_authenticated/app/hub/demand'
      path: '/demand'
      fullPath: '/app/hub/demand'
      preLoaderRoute: typeof AuthenticatedAppHubDemandRouteImport
      parentRoute: typeof AuthenticatedAppHubRoute
    }
    '/_authenticated/app/inteligencia/$media/$id': {
      id: '/_authenticated/app/inteligencia/$media/$id'
      path: '/inteligencia/$media/$id'
      fullPath: '/app/inteligencia/$media/$id'
      preLoaderRoute: typeof AuthenticatedAppInteligenciaMediaIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hub/u/$handle': {
      id: '/_authenticated/app/hub/u/$handle'
      path: '/u/$handle'
      fullPath: '/app/hub/u/$handle'
      preLoaderRoute: typeof AuthenticatedAppHubUHandleRouteImport
      parentRoute: typeof AuthenticatedAppHubRoute
    }
    '/_authenticated/app/hub/l/$id': {
      id: '/_authenticated/app/hub/l/$id'
      path: '/l/$id'
      fullPath: '/app/hub/l/$id'
      preLoaderRoute: typeof AuthenticatedAppHubLIdRouteImport
      parentRoute: typeof AuthenticatedAppHubRoute
    }
  }
}

interface AuthenticatedAppHubRouteChildren {
  AuthenticatedAppHubDemandRoute: typeof AuthenticatedAppHubDemandRoute
  AuthenticatedAppHubMessagesRoute: typeof AuthenticatedAppHubMessagesRoute
  AuthenticatedAppHubNewRoute: typeof AuthenticatedAppHubNewRoute
  AuthenticatedAppHubRankingRoute: typeof AuthenticatedAppHubRankingRoute
  AuthenticatedAppHubServicesRoute: typeof AuthenticatedAppHubServicesRoute
  AuthenticatedAppHubVerificationRoute: typeof AuthenticatedAppHubVerificationRoute
  AuthenticatedAppHubIndexRoute: typeof AuthenticatedAppHubIndexRoute
  AuthenticatedAppHubLIdRoute: typeof AuthenticatedAppHubLIdRoute
  AuthenticatedAppHubUHandleRoute: typeof AuthenticatedAppHubUHandleRoute
}

const AuthenticatedAppHubRouteChildren: AuthenticatedAppHubRouteChildren = {
  AuthenticatedAppHubDemandRoute: AuthenticatedAppHubDemandRoute,
  AuthenticatedAppHubMessagesRoute: AuthenticatedAppHubMessagesRoute,
  AuthenticatedAppHubNewRoute: AuthenticatedAppHubNewRoute,
  AuthenticatedAppHubRankingRoute: AuthenticatedAppHubRankingRoute,
  AuthenticatedAppHubServicesRoute: AuthenticatedAppHubServicesRoute,
  AuthenticatedAppHubVerificationRoute: AuthenticatedAppHubVerificationRoute,
  AuthenticatedAppHubIndexRoute: AuthenticatedAppHubIndexRoute,
  AuthenticatedAppHubLIdRoute: AuthenticatedAppHubLIdRoute,
  AuthenticatedAppHubUHandleRoute: AuthenticatedAppHubUHandleRoute,
}

const AuthenticatedAppHubRouteWithChildren =
  AuthenticatedAppHubRoute._addFileChildren(AuthenticatedAppHubRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAchievementsRoute: typeof AuthenticatedAppAchievementsRoute
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppAiIntegrationRoute: typeof AuthenticatedAppAiIntegrationRoute
  AuthenticatedAppAjudaRoute: typeof AuthenticatedAppAjudaRoute
  AuthenticatedAppAlertsRoute: typeof AuthenticatedAppAlertsRoute
  AuthenticatedAppConteudosRoute: typeof AuthenticatedAppConteudosRoute
  AuthenticatedAppDetectorRoute: typeof AuthenticatedAppDetectorRoute
  AuthenticatedAppHubRoute: typeof AuthenticatedAppHubRouteWithChildren
  AuthenticatedAppPaginaRoute: typeof AuthenticatedAppPaginaRoute
  AuthenticatedAppRadarRoute: typeof AuthenticatedAppRadarRoute
  AuthenticatedAppRankingRoute: typeof AuthenticatedAppRankingRoute
  AuthenticatedAppResellerRoute: typeof AuthenticatedAppResellerRoute
  AuthenticatedAppStoreRoute: typeof AuthenticatedAppStoreRoute
  AuthenticatedAppSubscriptionRoute: typeof AuthenticatedAppSubscriptionRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppServersIdRoute: typeof AuthenticatedAppServersIdRoute
  AuthenticatedAppServersNewRoute: typeof AuthenticatedAppServersNewRoute
  AuthenticatedAppInteligenciaIndexRoute: typeof AuthenticatedAppInteligenciaIndexRoute
  AuthenticatedAppServersIndexRoute: typeof AuthenticatedAppServersIndexRoute
  AuthenticatedAppInteligenciaMediaIdRoute: typeof AuthenticatedAppInteligenciaMediaIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAchievementsRoute: AuthenticatedAppAchievementsRoute,
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppAiIntegrationRoute: AuthenticatedAppAiIntegrationRoute,
  AuthenticatedAppAjudaRoute: AuthenticatedAppAjudaRoute,
  AuthenticatedAppAlertsRoute: AuthenticatedAppAlertsRoute,
  AuthenticatedAppConteudosRoute: AuthenticatedAppConteudosRoute,
  AuthenticatedAppDetectorRoute: AuthenticatedAppDetectorRoute,
  AuthenticatedAppHubRoute: AuthenticatedAppHubRouteWithChildren,
  AuthenticatedAppPaginaRoute: AuthenticatedAppPaginaRoute,
  AuthenticatedAppRadarRoute: AuthenticatedAppRadarRoute,
  AuthenticatedAppRankingRoute: AuthenticatedAppRankingRoute,
  AuthenticatedAppResellerRoute: AuthenticatedAppResellerRoute,
  AuthenticatedAppStoreRoute: AuthenticatedAppStoreRoute,
  AuthenticatedAppSubscriptionRoute: AuthenticatedAppSubscriptionRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppServersIdRoute: AuthenticatedAppServersIdRoute,
  AuthenticatedAppServersNewRoute: AuthenticatedAppServersNewRoute,
  AuthenticatedAppInteligenciaIndexRoute:
    AuthenticatedAppInteligenciaIndexRoute,
  AuthenticatedAppServersIndexRoute: AuthenticatedAppServersIndexRoute,
  AuthenticatedAppInteligenciaMediaIdRoute:
    AuthenticatedAppInteligenciaMediaIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogComoEvitarQuedaIptvRoute: typeof BlogComoEvitarQuedaIptvRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogComoEvitarQuedaIptvRoute: BlogComoEvitarQuedaIptvRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AlertasTelegramRoute: AlertasTelegramRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  DnsRoute: DnsRoute,
  McpRoute: McpRoute,
  MonitoramentoDnsRoute: MonitoramentoDnsRoute,
  MonitoramentoIptvRoute: MonitoramentoIptvRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RevendedorStreamMonitorRoute: RevendedorStreamMonitorRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  StatusSlugRoute: StatusSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicRadarRoute: ApiPublicRadarRoute,
  ApiPublicCoreTaskRoute: ApiPublicCoreTaskRoute,
  ApiPublicCronCheckRoute: ApiPublicCronCheckRoute,
  ApiPublicCronDigestRoute: ApiPublicCronDigestRoute,
  ApiPublicCronIptvNotificationsRoute: ApiPublicCronIptvNotificationsRoute,
  ApiPublicCronNotificationsRoute: ApiPublicCronNotificationsRoute,
  ApiPublicRegionsReportRoute: ApiPublicRegionsReportRoute,
  ApiPublicRegionsTargetsRoute: ApiPublicRegionsTargetsRoute,
  ApiPublicRobotsTxtRoute: ApiPublicRobotsTxtRoute,
  ApiPublicSitemapXmlRoute: ApiPublicSitemapXmlRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
