/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppServersRouteImport } from './routes/_authenticated/app.servers'
import { Route as ApiPublicCronCheckRouteImport } from './routes/api/public/cron/check'
import { Route as AuthenticatedAppServersNewRouteImport } from './routes/_authenticated/app.servers.new'
import { Route as AuthenticatedAppServersIdRouteImport } from './routes/_authenticated/app.servers.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppServersRoute = AuthenticatedAppServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicCronCheckRoute = ApiPublicCronCheckRouteImport.update({
  id: '/api/public/cron/check',
  path: '/api/public/cron/check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppServersNewRoute =
  AuthenticatedAppServersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppServersRoute,
  } as any)
const AuthenticatedAppServersIdRoute =
  AuthenticatedAppServersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppServersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/servers': typeof AuthenticatedAppServersRouteWithChildren
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/servers/$id': typeof AuthenticatedAppServersIdRoute
  '/app/servers/new': typeof AuthenticatedAppServersNewRoute
  '/api/public/cron/check': typeof ApiPublicCronCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/servers': typeof AuthenticatedAppServersRouteWithChildren
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/servers/$id': typeof AuthenticatedAppServersIdRoute
  '/app/servers/new': typeof AuthenticatedAppServersNewRoute
  '/api/public/cron/check': typeof ApiPublicCronCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/servers': typeof AuthenticatedAppServersRouteWithChildren
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/servers/$id': typeof AuthenticatedAppServersIdRoute
  '/_authenticated/app/servers/new': typeof AuthenticatedAppServersNewRoute
  '/api/public/cron/check': typeof ApiPublicCronCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/app/servers'
    | '/app/'
    | '/app/servers/$id'
    | '/app/servers/new'
    | '/api/public/cron/check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/servers'
    | '/app'
    | '/app/servers/$id'
    | '/app/servers/new'
    | '/api/public/cron/check'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/servers'
    | '/_authenticated/app/'
    | '/_authenticated/app/servers/$id'
    | '/_authenticated/app/servers/new'
    | '/api/public/cron/check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicCronCheckRoute: typeof ApiPublicCronCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/servers': {
      id: '/_authenticated/app/servers'
      path: '/servers'
      fullPath: '/app/servers'
      preLoaderRoute: typeof AuthenticatedAppServersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/cron/check': {
      id: '/api/public/cron/check'
      path: '/api/public/cron/check'
      fullPath: '/api/public/cron/check'
      preLoaderRoute: typeof ApiPublicCronCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/servers/new': {
      id: '/_authenticated/app/servers/new'
      path: '/new'
      fullPath: '/app/servers/new'
      preLoaderRoute: typeof AuthenticatedAppServersNewRouteImport
      parentRoute: typeof AuthenticatedAppServersRoute
    }
    '/_authenticated/app/servers/$id': {
      id: '/_authenticated/app/servers/$id'
      path: '/$id'
      fullPath: '/app/servers/$id'
      preLoaderRoute: typeof AuthenticatedAppServersIdRouteImport
      parentRoute: typeof AuthenticatedAppServersRoute
    }
  }
}

interface AuthenticatedAppServersRouteChildren {
  AuthenticatedAppServersIdRoute: typeof AuthenticatedAppServersIdRoute
  AuthenticatedAppServersNewRoute: typeof AuthenticatedAppServersNewRoute
}

const AuthenticatedAppServersRouteChildren: AuthenticatedAppServersRouteChildren =
  {
    AuthenticatedAppServersIdRoute: AuthenticatedAppServersIdRoute,
    AuthenticatedAppServersNewRoute: AuthenticatedAppServersNewRoute,
  }

const AuthenticatedAppServersRouteWithChildren =
  AuthenticatedAppServersRoute._addFileChildren(
    AuthenticatedAppServersRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppServersRoute: typeof AuthenticatedAppServersRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppServersRoute: AuthenticatedAppServersRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicCronCheckRoute: ApiPublicCronCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
